Merged 12.1 branch into dev
giffel99/communication-distributed-system-app pull request #10
Opened 2021-02-23 08:22 UTC by Hentoo

2021-02-23 08:42 UTC, giffel99 approved these changes
Good job mate!

2021-02-24 13:32 UTC, amandadehlen requested changes
![image](https://user-images.githubusercontent.com/43412147/109007709-bbac0f00-76ac-11eb-9878-5c66d010ce84.png)
"dead code", bör inte ligga där inne. (vet inte om det är du som har skapat det men tänker det ska flyttas fortfarande)

2021-02-24 13:35 UTC, amandadehlen commented
förutom kommentaren ovan så funkade det bra

2021-02-24 13:36 UTC, amandadehlen approved these changes
Jag approvar, så kan du väl ändra det ovan och merga in dev i den här branchen först innan du mergar in den här branchen i dev

2021-02-25 14:37 UTC, merged