21.1 Update password page when login for the first time
giffel99/communication-distributed-system-app pull request #11
Opened 2021-02-23 09:03 UTC by amandadehlen

2021-02-23 10:49 UTC, Hentoo submitted a review, later dismissed

2021-02-24 11:16 UTC, amandadehlen commented
Sätt firstLogin på användaren som true och logga sen in. Då kommer du tas till update password-sidan när du loggas in. När du ändrat lösenord så kan du logga ut och sen logga in med det nya lösenordet. 
Testa också felmeddelande
 - får kort lösenord
 - lösenorden matchar inte
 - ett av dom är inte ifylld

2021-02-25 14:10 UTC, giffel99 reviewed
Det borde finnas ett felmeddelande ifall new password och verify password inte matchar varandra. Ifall felmeddelande inte är en del av denna PR så ignorera meddelandet

2021-02-25 14:14 UTC, giffel99 requested changes
Det borde ges felmeddelande ifall lösen inte matchar varandra

2021-02-26 12:16 UTC, giffel99 submitted a review, later dismissed

2021-02-26 13:38 UTC, Hentoo approved these changes

2021-02-26 13:41 UTC, giffel99 approved these changes

2021-02-26 13:41 UTC, merged