10.1 Changed made in Login.dart file.
giffel99/communication-distributed-system-app pull request #12
Opened 2021-02-24 10:25 UTC by giffel99

2021-02-24 13:38 UTC, amandadehlen approved these changes
funderar på om vi vill säga vilket som är fel eller om vi vill bara säga att kombinationen är fel? Vet att vissa sidor bara säger att kombinationen är fel. Men approvar så får du tänka kring hur vi vill göra där. Ser bra ut annars iaf

2021-02-26 10:47 UTC, Hentoo requested changes

2021-02-26 10:47 UTC, Hentoo commented on elvaett/lib/screens/login.dart
> +                  errorText: _wrongPassword ? 'Wrong password entered' : null),
Incorrect password?
istället för "Wrong password entered"

2021-02-26 10:47 UTC, Hentoo commented on elvaett/lib/screens/login.dart
> +                errorText: _wrongEmail ? 'Wrong Email entered' : null),
Incorrect email?

Istället för Wrong Email entered

2021-02-26 12:16 UTC, Hentoo approved these changes
Looks good!

2021-02-26 13:14 UTC, amandadehlen approved these changes

2021-02-26 13:14 UTC, merged