12.3 Stops sharing position when signing out + refactored code in dashboard and locationButton
giffel99/communication-distributed-system-app pull request #16
Opened 2021-02-26 16:50 UTC by amandadehlen

2021-02-26 19:08 UTC, Hentoo approved these changes
Snyggt! Kommer förmodligen behöva flytta all logik till requestboxarna sen eftersom de har share location knappen

2021-02-28 18:33 UTC, giffel99 commented on elvaett/lib/services/database_service.dart
> +  static void removeUserPosition(String userId) {
På rad 59 ni locationButton klassen så har du inte ändrat till den nya metoden

2021-02-28 18:34 UTC, giffel99 requested changes
Lämnade en kommentar ovan att du fortfarande kallar på en metod som inte längre finns. LocationButton. Rad 59

2021-03-01 10:46 UTC, Hentoo approved these changes

2021-03-01 10:46 UTC, giffel99 approved these changes

2021-03-01 10:51 UTC, merged