Now name shows correctly on dashboard
giffel99/communication-distributed-system-app pull request #22
Opened 2021-03-17 10:23 UTC by Hentoo

2021-03-17 13:19 UTC, giffel99 approved these changes
Fint gjort!

2021-03-18 18:28 UTC, amandadehlen reviewed
![image](https://user-images.githubusercontent.com/43412147/111677829-e60e6980-881f-11eb-94be-de3c2218413c.png)
Jag får error om man inte har satt ett namn. Så borde hantera det.

2021-03-18 18:34 UTC, amandadehlen requested changes
![image](https://user-images.githubusercontent.com/43412147/111677829-e60e6980-881f-11eb-94be-de3c2218413c.png)
Jag får error om man inte har satt ett namn. Så borde hantera det.

2021-03-18 18:46 UTC, amandadehlen commented
Får även error på första "uppmålningen", när man försöker hämta snapshotet men misslyckas. På andra omgången lyckas man och visar namnet

2021-03-21 13:43 UTC, giffel99 approved these changes

2021-03-24 17:53 UTC, amandadehlen approved these changes

2021-03-25 12:05 UTC, giffel99 approved these changes

2021-03-25 12:05 UTC, giffel99 commented on elvaett/lib/services/database_service.dart
> +  }
Detta du la till?

2021-03-25 12:16 UTC, merged