Position sharing now ends when time exceeds endTime
giffel99/communication-distributed-system-app pull request #34
Opened 2021-03-30 12:38 UTC by Hentoo

2021-03-30 13:16 UTC, amandadehlen requested changes
Man får ingen feedback på att man inte kan dela position för att det är efter sluttid

2021-03-30 19:21 UTC, giffel99 submitted a review, later dismissed
Håller med det amanda sa. Man borde kanske få en notis att tiden är slut. Sen är väl nästa steg att  request ikonen inte går att klickas alls och visuellt visar att den inte går att aktivera

2021-03-31 14:02 UTC, Hentoo commented on elvaett/lib/services/database_service.dart
> +    return timestamp;
return null skapade bugg så tog bara timestamp, kanske kan ta bort den första timestampen

2021-03-31 14:06 UTC, Hentoo commented on elvaett/lib/services/database_service.dart
> +    return timestamp;
sen angående kommentaren så håller jag med, tänkte att så fort vi löser notiser kan vi skicka notiser men jag ska fixa det som amanda sa

2021-04-02 07:53 UTC, giffel99 approved these changes

2021-04-02 08:38 UTC, amandadehlen commented on elvaett/lib/services/database_service.dart
> +    return timestamp;
Tänker just om man inte kan börja dela så ska det inte bara vara att det inte går att klicka på den

2021-04-02 08:45 UTC, amandadehlen commented
![Uploading image.png…]()

2021-04-02 08:45 UTC, amandadehlen commented
![image](https://user-images.githubusercontent.com/43412147/113399442-888e2700-93a0-11eb-9033-11494cb54c23.png)

2021-04-02 08:46 UTC, amandadehlen commented
![image](https://user-images.githubusercontent.com/43412147/113399509-9c398d80-93a0-11eb-94a3-d4567c424e8d.png)

2021-04-02 08:49 UTC, amandadehlen approved these changes

2021-04-02 08:50 UTC, merged